version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_DB=weather_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - postgres_db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
